version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
